language: ruby
dist: xenial
rvm:
  - 2.5

addons:
  ssh_known_hosts:
  - dadastaging.okfn.fr
before_install:
# install ansible for provisioning of server (setup db, nginx, MTA...)
- sudo add-apt-repository --yes ppa:ansible/ansible
- sudo apt-get update -y
- sudo apt-get upgrade -y
- sudo apt-get install ansible
# install capistrano and related packages
- gem install bundler capistrano
install:
- eval "$(ssh-agent -s)" #start the ssh agent
- openssl aes-256-cbc -K $encrypted_e64c44062370_key -iv $encrypted_e64c44062370_iv -in ssh-privkey-staging.pem.enc -out ssh-privkey-staging.pem -d
- chmod 600 ssh-privkey-staging.pem
- ssh-add ssh-privkey-staging.pem
before_script:

script:
- ansible-playbook -i ansible/ansible_inventory ansible/site.yml
