---
dependencies:
  - role: anxs.postgresql
    become: yes
    postgresql_version: 9.6
    postgresql_users:
      - name: "{{ db_user_name }}"
        pass: "{{ db_user_password }}"
        encrypted: yes
    postgresql_listen_addresses:
      - "*"
    # WAL settings for wal-g backup
    postgresql_wal_level: "replica"
    postgresql_archive_mode: "on"
    postgresql_archive_timeout: 120
    postgresql_archive_command: "AWS_ENDPOINT=https://sos-ch-gva-2.exo.io WALG_S3_PREFIX=s3://madada-db-backup AWS_ACCESS_KEY_ID={{ backup_storage_access_key }} AWS_SECRET_ACCESS_KEY={{ backup_storage_secret_key }} /usr/local/bin/wal-g wal-push %p"
