---
user_support_emails: dada@where.tf

db_name_production: alaveteli_production
db_name_test: alaveteli_test
db_user_password: "{{ lookup('env', 'DB_USER_PASSWORD_STAGING') }}"

# this one is in vault.yml, encrypted
rails_secret_key_base: "{{ vault_rails_secret_key_base }}"

site_domain: dadastaging.okfn.fr

# these env vars come from travis secret variables
incoming_email_secret: "{{ lookup('env', 'INCOMING_EMAIL_SECRET_STAGING') }}"

emergency_admin_password: "{{ lookup('env', 'EMERGENCY_ADMIN_PASSWORD_STAGING') }}"

recaptcha_site_key: 6LcrJJ4UAAAAAAokc-1h06cfzlQgTsjeQMsyd7en

recaptcha_secret_key: "{{ lookup('env', 'RECAPTCHA_SECRET_KEY') }}"

# send all requests to public bodies to this email instead
# useful for staging, set to empty string in production
override_all_public_body_emails: dada@where.tf

# change the prefix for staging/production
# to limit confusion
incoming_email_prefix: dadastaging+

# git branch in theme repo to use for the site
# the production site should use master
theme_branch: staging
